//import './instance'
//import './lifecycle'
//import './data-bing'
//import './computed'
//import './directive'
// import './component/index.js'
//import './component/extend'
//import './component/extend2'
//import './component/parent'
import './component/model1'
//import './component/model2'
//import './component/slot(2.5)'
//import './component/slot(2.6)'
//import './component/parent'
//import './component/parent2'
// import './component/render'

